services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    restart: unless-stopped
