# Use official Python 3.12 image
FROM python:3.12-slim-bullseye

WORKDIR /app

RUN pip install fastapi uvicorn python-multipart psycopg[binary] sqlalchemy alembic asyncpg

COPY . /app

# Environmental vars
ENV PYTHONPATH=/app

# Run the app with uvicorn
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
