services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
        - ./.secrets.toml:/app/.secrets.toml:ro
    depends_on:
      - db
      - nats
    environment:
      - RUNNING_IN_DOCKER=true

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    ports:
      - "5430:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  nats:
    image: nats:latest
    container_name: nats-server
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
    - ./nats/config:/config
    - ./nats/data:/data
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: image-worker
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on:
      - db
      - nats
    restart: unless-stopped

volumes:
  pgdata: